DEFINE USER_NAME = &&1
DEFINE DATA_TABLESPACE_NAME = '&&USER_NAME._DATA'

CREATE TABLE "EVENTS" (
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	"EVENT_NAME" VARCHAR2(255) NOT NULL,
	"EVENT_MINUTE" NUMBER NOT NULL,
	"PLAYER_ID" NUMBER NOT NULL,
	"MATCH_ID" NUMBER NOT NULL) TABLESPACE &&DATA_TABLESPACE_NAME
/