DEFINE USER_NAME = &&1
DEFINE DATA_TABLESPACE_NAME = '&&USER_NAME._DATA'

CREATE TABLE "MATCHES" (
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	"MATCH_DATE" VARCHAR2(255) NOT NULL,
	"STADIUM_ID" NUMBER NOT NULL,
	"STAGE_ID" NUMBER NOT NULL) TABLESPACE &&DATA_TABLESPACE_NAME
/