DEFINE USER_NAME = &&1
DEFINE DATA_TABLESPACE_NAME = '&&USER_NAME._DATA'

CREATE TABLE "TICKETS_INFO" (
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	"AVERAGE_PRICE" NUMBER NOT NULL,
	"SOLD_AMOUNT" NUMBER NOT NULL,
	"MATCH_ID" NUMBER NOT NULL) TABLESPACE &&DATA_TABLESPACE_NAME
/