--PK

ALTER TABLE "TEAMS" ADD constraint TEAMS_PK PRIMARY KEY ("ID");
ALTER TABLE "PLAYERS" ADD constraint PLAYERS_PK PRIMARY KEY ("ID");
ALTER TABLE "MATCHES" ADD constraint MATCHES_PK PRIMARY KEY ("ID");
ALTER TABLE "STADIUMS" ADD constraint STADIUMS_PK PRIMARY KEY ("ID");
ALTER TABLE "TEAMS_IN_MATCHES" ADD constraint TEAMS_IN_MATCHES_PK PRIMARY KEY ("ID");
ALTER TABLE "EVENTS" ADD constraint EVENTS_PK PRIMARY KEY ("ID");
ALTER TABLE "STAGES" ADD constraint STAGES_PK PRIMARY KEY ("ID");
ALTER TABLE "COACHES_HISTORY" ADD constraint COACHES_HISTORY_PK PRIMARY KEY ("ID");
ALTER TABLE "PLAYERS_HISTORY" ADD constraint PLAYERS_HISTORY_PK PRIMARY KEY ("ID");
ALTER TABLE "TICKETS_INFO" ADD constraint TICKETS_INFO_PK PRIMARY KEY ("ID");
ALTER TABLE "COACHES" ADD constraint COACHES_PK PRIMARY KEY ("ID");
ALTER TABLE "LEAGUES" ADD constraint LEAGUES_PK PRIMARY KEY ("ID");


--FK

ALTER TABLE "TEAMS" ADD CONSTRAINT "TEAMS_fk0" FOREIGN KEY ("STADIUM_ID") REFERENCES "STADIUMS"("ID") ON DELETE SET NULL;


ALTER TABLE "MATCHES" ADD CONSTRAINT "MATCHES_fk0" FOREIGN KEY ("STADIUM_ID") REFERENCES "STADIUMS"("ID") ON DELETE CASCADE;
ALTER TABLE "MATCHES" ADD CONSTRAINT "MATCHES_fk1" FOREIGN KEY ("STAGE_ID") REFERENCES "STAGES"("ID") ON DELETE CASCADE;


ALTER TABLE "TEAMS_IN_MATCHES" ADD CONSTRAINT "TEAMS_IN_MATCHES_fk0" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAMS"("ID") ON DELETE CASCADE;
ALTER TABLE "TEAMS_IN_MATCHES" ADD CONSTRAINT "TEAMS_IN_MATCHES_fk1" FOREIGN KEY ("MATCH_ID") REFERENCES "MATCHES"("ID") ON DELETE CASCADE;

ALTER TABLE "EVENTS" ADD CONSTRAINT "EVENTS_fk0" FOREIGN KEY ("PLAYER_ID") REFERENCES "PLAYERS"("ID") ON DELETE CASCADE;
ALTER TABLE "EVENTS" ADD CONSTRAINT "EVENTS_fk1" FOREIGN KEY ("MATCH_ID") REFERENCES "MATCHES"("ID") ON DELETE CASCADE;

ALTER TABLE "STAGES" ADD CONSTRAINT "STAGES_fk0" FOREIGN KEY ("LEAGUE_ID") REFERENCES "LEAGUES"("ID") ON DELETE CASCADE;

ALTER TABLE "COACHES_HISTORY" ADD CONSTRAINT "COACHES_HISTORY_fk0" FOREIGN KEY ("STAGE_ID") REFERENCES "STAGES"("ID") ON DELETE CASCADE;
ALTER TABLE "COACHES_HISTORY" ADD CONSTRAINT "COACHES_HISTORY_fk1" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAMS"("ID") ON DELETE CASCADE;
ALTER TABLE "COACHES_HISTORY" ADD CONSTRAINT "COACHES_HISTORY_fk2" FOREIGN KEY ("COACH_ID") REFERENCES "COACHES"("ID") ON DELETE CASCADE;

ALTER TABLE "PLAYERS_HISTORY" ADD CONSTRAINT "PLAYERS_HISTORY_fk0" FOREIGN KEY ("PLAYER_ID") REFERENCES "PLAYERS"("ID") ON DELETE CASCADE;
ALTER TABLE "PLAYERS_HISTORY" ADD CONSTRAINT "PLAYERS_HISTORY_fk1" FOREIGN KEY ("STAGE_ID") REFERENCES "STAGES"("ID") ON DELETE CASCADE;
ALTER TABLE "PLAYERS_HISTORY" ADD CONSTRAINT "PLAYERS_HISTORY_fk2" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAMS"("ID") ON DELETE CASCADE;

ALTER TABLE "TICKETS_INFO" ADD CONSTRAINT "TICKETS_INFO_fk0" FOREIGN KEY ("MATCH_ID") REFERENCES "MATCHES"("ID") ON DELETE CASCADE;