CREATE TABLE "COACHES" (
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	"COACH_NAME" VARCHAR2(255) NOT NULL,
	"COACH_BIRTH_YEAR" NUMBER,
	"COACH_RANK" VARCHAR2(255));