DEFINE USER_NAME = &&1
DEFINE DATA_TABLESPACE_NAME = '&&USER_NAME._DATA'

CREATE TABLE "COACHES" (
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	"COACH_NAME" VARCHAR2(255) NOT NULL,
	"COACH_BIRTH_YEAR" NUMBER,
	"COACH_RANK" VARCHAR2(255)) TABLESPACE &&DATA_TABLESPACE_NAME
/