DELETE FROM "PLAYERS_HISTORY";
DELETE FROM "COACHES_HISTORY";
DELETE FROM "TICKETS_INFO";
DELETE FROM "EVENTS";
DELETE FROM "MATCHES";
DELETE FROM "STAGES";
DELETE FROM "LEAGUES";
DELETE FROM "TEAMS_IN_MATCHES";
DELETE FROM "STADIUMS";
DELETE FROM "PLAYERS";
DELETE FROM "COACHES";
DELETE FROM "TEAMS";
DELETE FROM "DATA_TABLE";

COMMIT;