SET SERVEROUTPUT ON;

DECLARE ROWSCOUNT NUMBER;

BEGIN

SELECT COUNT(*) INTO ROWSCOUNT FROM COACHES;
DBMS_OUTPUT.PUT_LINE('COACHES - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM COACHES_HISTORY;
DBMS_OUTPUT.PUT_LINE('COACHES_HISTORY - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM TEAMS;
DBMS_OUTPUT.PUT_LINE('TEAMS - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM PLAYERS_HISTORY;
DBMS_OUTPUT.PUT_LINE('PLAYERS_HISTORY - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM PLAYERS;
DBMS_OUTPUT.PUT_LINE('PLAYERS - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM STADIUMS;
DBMS_OUTPUT.PUT_LINE('STADIUMS - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM TEAMS_IN_MATCHES;
DBMS_OUTPUT.PUT_LINE('TEAMS_IN_MATCHES - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM EVENTS;
DBMS_OUTPUT.PUT_LINE('EVENTS - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM LEAGUES;
DBMS_OUTPUT.PUT_LINE('LEAGUES - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM STAGES;
DBMS_OUTPUT.PUT_LINE('STAGES - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM MATCHES;
DBMS_OUTPUT.PUT_LINE('MATCHES - count of rows: ' || ROWSCOUNT);

SELECT COUNT(*) INTO ROWSCOUNT FROM TICKETS_INFO;
DBMS_OUTPUT.PUT_LINE('TICKETS_INFO - count of rows: ' || ROWSCOUNT);

END;