SELECT 
	L.YEAR Championship,
	L.LEAGUE_NAME League,
	T1.TEAM_FOUNDATION_YEAR Founded_Team_1,
	C1.COACH_NAME Trainer_Team_1,
	T2.TEAM_FOUNDATION_YEAR Founded_Team_2,
	T2.COACH_NAME Trainer_Team_2,
	T1.TEAM_NAME Team_1,
	T2.TEAM_NAME Team_2,
	E.EVENT_NAME Event,
	P.PLAYER_NAME Player_Last_Name,
	T.TEAM_NAME Player_Team,
	P.PLAYER_ROLE Position,
	E.EVENT_MINUTE Event_Time,
	M.MATCH_DATE Date,
	STAD.CITY_NAME Location,
	STAD.STADIUM_NAME Venue,
	STAD.STADIUM_CAPACITY Capacity,
	TI.AVERAGE_PRICE Avg_price,
	TI.SOLD_AMOUNT tickets_sold
FROM PLAYER P
	 LEFT JOIN EVENTS E ON P.ID = E.PLAYER_ID
	 LEFT JOIN MATCHES M ON M.ID = E.MATCH_ID
	 LEFT JOIN TICKETS_INFO TI ON M.ID = TI.MATCH_ID
	 LEFT JOIN STADIUMS STAD ON M.STADIUM_ID = STAD.ID
	 LEFT JOIN TEAMS_IN_MATCHES TIM ON M.ID = TIM.MATCH_ID
	 LEFT JOIN TEAMS T1 ON TIM.TEAM_ID = TEAMS.ID
	 LEFT JOIN TEAMS T2 ON TIM.TEAM_ID = TEAMS.ID AND NOT TIM.TEAM_ID = T1.ID
	 LEFT JOIN STAGES STAG ON M.STAGE_ID = STAG.ID
	 LEFT JOIN LEAGUES L ON STAG.LEAGUE_ID = L.ID
	 LEFT JOIN COACHES_HISTORY CH ON STAG.ID = CH.STAGE_ID
	 LEFT JOIN COACHES C ON CH.COACH_ID = C.ID
	 LEFT JOIN TEAMS T ON T.ID = TIM.TEAM_ID AND TIM.MATCH_ID = M.ID AND M.ID = E.MATCH_ID AND E.PLAYER_ID = P.ID

COMMIT;