SELECT 
	L.LEAGUE_YEAR Championship,
	L.LEAGUE_NAME League,
	T1.TEAM_FOUNDATION_YEAR Founded_Team_1,
	C1.COACH_NAME Trainer_Team_1,
	T2.TEAM_FOUNDATION_YEAR Founded_Team_2,
	C2.COACH_NAME Trainer_Team_2,
	T1.TEAM_NAME Team_1,
	T2.TEAM_NAME Team_2,
	E.EVENT_NAME Event,
	P.PLAYER_NAME Player_Last_Name,
	T.TEAM_NAME Player_Team,
	P.PLAYER_ROLE Position,
	E.EVENT_MINUTE Event_Time,
	M.MATCH_DATE Date_Time,
	STAD.CITY_NAME Location,
	STAD.STADIUM_NAME Venue,
	STAD.STADIUM_CAPACITY Capacity,
	TI.AVERAGE_PRICE Avg_price,
	TI.SOLD_AMOUNT tickets_sold
FROM EVENTS E, TICKETS_INFO TI, MATCHES M, PLAYERS P, PLAYERS_HISTORY PH, TEAMS_IN_MATCHES TIM, STAGES STAG, LEAGUES L, COACHES_HISTORY CH1, COACHES_HISTORY CH2, STADIUMS STAD, COACHES C1, COACHES C2, TEAMS T1, TEAMS T2, TEAMS T
WHERE
	E.PLAYER_ID = P.ID
	AND E.MATCH_ID = M.ID
	AND M.ID = TI.MATCH_ID
	AND M.STAGE_ID = STAG.ID
	AND STAG.LEAGUE_ID = L.ID
AND STAG.ID = CH.STAGE_ID
AND PH.PLAYER_ID = P.ID
	AND PH.STAGE_ID = STAG.ID
	AND M.STADIUM_ID = STAD.ID
	AND TIM.TEAM_ID = T1.ID
	AND TIM.TEAM_ID = T2.ID
AND NOT T1.ID = T2.ID
AND PH.TEAM_ID = T.ID
AND CH1.TEAM_ID = T1.ID
AND CH1.COACH_ID = C1.ID
AND CH2.TEAM_ID = T2.ID
AND CH2.COACH_ID = C2.ID
	AND CH1.STAGE_ID = STAG.ID
	AND CH2.STAGE_ID = STAG.ID
AND PH.STAGE_ID = STAG.ID
AND PH.TEAM_ID = T.ID





FROM MATCHES M
LEFT JOIN TEAMS_IN_MATCHES TIM ON TIM.MATCH_ID = M.ID
LEFT JOIN TEAMS T ON T.ID = TIM.TEAM_ID
LEFT JOIN STADIUMS STAD ON STAD.ID = M.STADIUM_ID

LEFT JOIN EVENTS EV ON M.MATCH_ID = EV.MATCH_ID
LEFT JOIN PLAYERS PS ON EV.PLAYER_NAME = PS.NAME
LEFT JOIN SEASONS S ON M.SEASON_ID = S.SEASON_ID
LEFT JOIN LEAGUES LG ON TM1.LEAGUE_ID = LG.LEAGUE_ID
LEFT JOIN STADIUMS ST ON TM1.TEAM_ID = ST.TEAM_ID
LEFT JOIN COACHES CH1 ON TM1.TEAM_ID = CH1.TEAM_ID
LEFT JOIN COACHES CH2 ON TM2.TEAM_ID = CH2.TEAM_ID
ORDER BY FOUNDED_TEAM_1 DESC, EVENT ASC;





COMMIT;