CREATE TABLE DATA_TABLE (
    Championship NUMBER,
    League VARCHAR2(255),
    Founded_Team_1 NUMBER,
    Trainer_Team_1 VARCHAR2(255),
    Founded_Team_2 NUMBER,
    Trainer_Team_2 VARCHAR2(255),
    Team_1 VARCHAR2(255),
    Team_2 VARCHAR2(255),
    Event VARCHAR2(255),
    Player_Last_Name VARCHAR2(255),
    Player_Team VARCHAR2(255),
    Position VARCHAR2(255),
    Event_Time NUMBER,
    Date_Time VARCHAR2(255),
    Location VARCHAR2(255),
    Venue VARCHAR2(255),
    Capacity NUMBER,
    Avg_price NUMBER,
    tickets_sold NUMBER
);